<?
$PERM["adverts"]["7"]="W";
$PERM["adverts"]["6"]="W";
$PERM["saler_account"]["7"]="W";
$PERM["saler_account"]["6"]="W";
$PERM["saler_account"]["*"]="D";
$PERM["buyer_account"]["8"]="W";
$PERM["buyer_account"]["6"]="W";
$PERM["buyer_account"]["*"]="D";
$PERM["about_service"]["6"]="W";
$PERM["search"]["6"]="W";
$PERM["index.php"]["6"]="W";
$PERM["/"]["*"]="R";
?>