<?
$PERM["buyer_account"]["*"]="D";
$PERM["buyer_account"]["8"]="X";
$PERM["buyer_account"]["6"]="X";
$PERM["saler_account"]["*"]="D";
$PERM["saler_account"]["7"]="X";
$PERM["saler_account"]["6"]="X";
$PERM["search"]["6"]="W";
$PERM["index.php"]["6"]="W";
$PERM["/"]["*"]="R";
?>