<?
$PERM[".top.menu.php"]["9"]="W";
$PERM[".bottom.menu.php"]["9"]="W";
$PERM["adverts"]["7"]="W";
$PERM["adverts"]["6"]="W";
$PERM["adverts"]["9"]="W";
$PERM["saler_account"]["6"]="W";
$PERM["saler_account"]["9"]="W";
$PERM["saler_account"]["*"]="D";
$PERM["saler_account"]["7"]="W";
$PERM["buyer_account"]["6"]="W";
$PERM["buyer_account"]["9"]="W";
$PERM["buyer_account"]["*"]="D";
$PERM["buyer_account"]["8"]="W";
$PERM["about_service"]["6"]="W";
$PERM["about_service"]["9"]="W";
$PERM["bitrix"]["*"]="D";
$PERM["search"]["6"]="W";
$PERM["index.php"]["6"]="W";
$PERM["/"]["*"]="R";
?>